version: '3.8'

services:
  postgres:
    image: postgres:14
    networks:
      - default
      - ext_comp
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

  redis:
    image: redis:latest
    networks:
      - default
      - ext_comp
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: always

volumes:
  postgres-db-volume:
    external: true
    name: "airflow-study_postgres-db-volume"

networks:
  default:
    external: true
    name: airflow
  ext_comp:
    external: true
    name: ext_comp
